version: "3.8"
name: "chatbot"
services:
  backend:
    build: ./api
    restart: on-failure
    ports:
      - "9000:9000"

  frontend:
    build: ./frontend
    restart: on-failure
    ports:
      - "8080:80"
    depends_on:
      - backend
