version: "3.8"
name: "chatbot"
services:
  backend:
    build: ./api
    restart: on-failure
    ports:
      - "9000:9000"

  frontend:
    build:
      context: ./frontend
      args:
          NODE_ENV: ${NODE_ENV}  # On passe l'argument NODE_ENV
    restart: on-failure
    ports:
      - "8080:80"
    depends_on:
      - backend
